name: TidalLib

on: [push, pull_request]

jobs:
  Build:
    name: Build TidalLib
    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  

    - name: Checkout TidalLib repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: TidalLib

    - name: Checkout AIGS repo
      uses: actions/checkout@v3
      with:
        repository: AIGMix/AIGS
        path: AIGS
        
    - name: Intall AIGS dependencies
      run: msbuild -t:restore -p:RestorePackagesConfig=true
      working-directory: AIGS

    - name: Intall TidalLib dependencies
      run: msbuild -t:restore -p:RestorePackagesConfig=true
      working-directory: TidalLib\TidalLib

    - name: Build AIGS artifact
      run: msbuild AIGS.csproj -verbosity:diag -property:Configuration=Debug
      working-directory: AIGS

    - name: Build TidalLib artifact
      run: msbuild TidalLib.csproj -verbosity:diag -property:Configuration=Debug
      working-directory: TidalLib\TidalLib

    - name: Upload TidalLib artifact
      uses: actions/upload-artifact@v3
      with:
        name: TidalLib
        path: TidalLib\TidalLib\bin\Debug\TidalLib.dll
